name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:

jobs:
    test:
        name: "Reproduce tox windows-latest issue"
        runs-on: windows-latest

        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v3

            - name: "Set up Python 3.8"
              uses: actions/setup-python@v4
              with:
                  python-version: "3.8"

            - name: "Install dependencies"
              run: |
                  python -m pip install --upgrade pip
                  # tox version: https://github.com/tox-dev/tox/issues/2778
                  python -m pip install tox tox-gh-actions

            - name: "Run tox"
              run: |
                  tox -rvv
              env:
                  PLATFORM: windows-latest
